### ISSUE TITLE
Kronoterm HP modbus documentation

### ISSUE THREAD

**Issue by redlordt** [kosl/kronoterm2mqtt#2]
Hi,

I have recently found your repository for Kronoterm heat pump modbus access. I have this kind of heat pump and I've been analyzing a possibility to access to it. Unfortunately my TEX socket is used to connect to outdoor unit. Anyway I've taped to this connection and get modbus communication. Unfortunately Kronoterm website is lack of technical documentation connected with modbus access. In your project you have mentioned, in references, about three pdf's from Kronoterm. Is it possible to get it  from you, if it is no problem ?

kind regards
Tom
my email: redlord@poczta.onet.pl

**Comment by kosl** [comment]
Well, I have only Documentation listed at the bottom of the README that is referencing ETERA, WPG, ADAPT, VERSI, WPLV models. I will send you english version. I recommend to contact support@kronoterm.com for your model BMS instructions and send me that to revise.

**Comment by Fofuracer** [comment]
![Mainboard_TT3000Unit](https://github.com/user-attachments/assets/0b1f9749-18ff-4f87-9261-86f8a40e6601)
![Board_backside-controlpanel](https://github.com/user-attachments/assets/ece1781d-6df8-48b7-a2fd-11c9714bf28d)
Hello, at first, great work! I'm also owning a Heatpump from Kronoterm, and also want to try to get it connected to homeassistant. Unfortunately my Pump is from the year 2010, and Kronoterm doesn't want to support this unit because it is located in austria. I already checked the controler Unit, it is a TT3000 and there's also a TEX connector on the board. I'd like to give it a try. Is there any  possibility, that I end up with a damaged and not working heatpump? Could you please also provide me your documentation you received from Kronoterm? Thank you in advance

**Comment by kosl** [comment]
Reference documentation attached. There are slight differences between old and new specs due to upgraded capabilities.
[Installation and Operating Manual for BMS System.pdf](https://github.com/user-attachments/files/17962066/Installation.and.Operating.Manual.for.BMS.System.pdf)
[22-16-17-4021-05_Modbus_BMS_TT3000web.pdf](https://github.com/user-attachments/files/17962067/22-16-17-4021-05_Modbus_BMS_TT3000web.pdf)
As written in the documentation, your baudrate should be 19200. Test with a little example as described.

**Comment by kosl** [comment]
[Navodila za priklop in uporabo CNS sistema.pdf](https://github.com/user-attachments/files/22581626/Navodila.za.priklop.in.uporabo.CNS.sistema.pdf)
